services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: "mongodb+srv://kumar:PZjSt7uKL1JHCE8V@cluster0.b2emiit.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      JWT_SECRET: "your_jwt_secret_key_here"
      PORT: "5000"
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/node_modules

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
